version: '3'
services:
  db:
    image: mysql/mysql-server:5.7
    # ports:
    #   - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Aremaniak1_
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Aremaniak1_ 
      - MYSQL_DATABASE=course_scheduler   
  web:
    build: .
    # ports:
    #   - "5001:5001"
    volumes:
      - ".:/app"
    depends_on:
      - db
    links:
      - "db:database"